name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          # echo "Lorem ipsum" > lorem_1.md  # create two example files
          # echo "dolor sit amet" > lorem_2.md
          mkdir output  # create output dir
          # this will also include README.md
          # echo "::set-env name=FILELIST::$(printf '"%s" ' *.md)"
          echo "::set-env name=FILELIST::$(printf '"%s" ' Statnice.md)"
      - uses: docker://pandoc/latex:2.9
        with:
          args: >- 
            --wrap=preserve
            --output=output/result.pdf ${{ env.FILELIST }}
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output

#name: Convert

#on: push

#jobs:
  #convert_via_pandoc:
    #runs-on: ubuntu-18.04
    #steps:
      # - run: echo "foo" > input.txt # create an example file
      # - uses: docker://pandoc/core:2.9
        #with:
          #args: >- # allows you to break string into multiple lines
            #--standalone
            #--output=Statnice.pdf
            #Statnice.md
